### ISSUE TITLE
[Venue Request]: Go Day Minna

### ISSUE THREAD

**Issue by Taiwrash** [gobridge/gdn#11]
### Hosting Group Name

GDN Minna | https://www.meetup.com/go-developers-network-minna/

### Event Location

Minna, Niger State, Nigeria

### Event Date

Saturday 9th September, 2023

### Start Time (UTC)

9a.m WAT

### Remote Meetup Option

No

### Contact Details

rasheedrtm1@gmail.com

### Code of Conduct

- [X] I agree to follow the GoBridge Code of Conduct

**Comment by nywilken** [comment]
Hi @Taiwrash I apologize for the late response but we had a hard time securing venues and sponsors.  I am keeping these issues open as we work to find ve yes in your area. 

I can not provide any further support at this time but if you are interested in hosting a virtual event. We can work to find a speaker in your time zone. 

Would you be up for a virtual speaker?


Alternatively, you may want to look into having a short networking meet/great session with your community at a free public location.  We can provide Zoom access if you wish to do something virtual.
