### ISSUE TITLE
[Sponsorship Request]: Go Day Minna

### ISSUE THREAD

**Issue by Taiwrash** [gobridge/gdn#12]
### Hosting Group Name

GDN Minna | https://www.meetup.com/go-developers-network-minna/

### Event Location

Minna, Niger State, Nigeria

### Event Date

Saturday 9th September, 2023

### Sponsorship Details

1. Food
2. Drinks
3. Stickers
4. Shirts
5. Banner
6. Jotter and other Writing Materials

### Contact Details (Optional)

rasheedrtm1@gmail.com

### Code of Conduct

- [X] I agree to follow the GoBridge Code of Conduct

**Comment by nywilken** [comment]
Closing as I would like to track this request for a sponsor on #11
